# Generated by Django 5.1.2 on 2024-10-30 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('produtosservico', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtosservico',
            name='produto',
            field=models.ForeignKey(help_text='Nome do produto utilizado', on_delete=django.db.models.deletion.PROTECT, related_name='produto', to='produtos.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='produtosservico',
            name='servico',
            field=models.ForeignKey(help_text='Nome do serviço realizado', on_delete=django.db.models.deletion.PROTECT, related_name='servico', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
