# Generated by Django 5.1.2 on 2024-11-06 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('ordemservicos', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(through='ordemservicos.OrdemServicos', to='servicos.servico', verbose_name='Serviço'),
        ),
    ]
